# Generated by Django 2.2.5 on 2019-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentifyFace', '0002_student_encodings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
