# Generated by Django 2.2.5 on 2019-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentifyFace', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(default=None, upload_to='logs/'),
            preserve_default=False,
        ),
    ]
